### ISSUE TITLE
Next Enhancements

### ISSUE THREAD

**Issue by pr0d7** [BuildAndDestroy/CoinMarketCap_API#1]
++ Add a section to show the total amount of 'Current Equity' for overall Portfolio balance

++ Under the 'Current Equity Limit' and new Overall Portfolio Balance limit the decimal places to 3.

++Add in a sort feature to sort by either Alphabetical / Highest coin or token balance

**Comment by pr0d7** [comment]
++ Add in 'importing' an existing portfolio.csv so that you don't have to manually retype out a long string

**Comment by BuildAndDestroy** [comment]
> ++ Under the 'Current Equity Limit' and new Overall Portfolio Balance limit the decimal places to 3.

This has been fixed and pushed to master branch, now under release 2.3-3space.decimal.

**Comment by BuildAndDestroy** [comment]
> ++ Add a section to show the total amount of 'Current Equity' for overall Portfolio balance

This has now been pushed to the master branch, version:
`2.3.4-totals`

**Comment by BuildAndDestroy** [comment]
Ok we have two objectives left:

> ++Add in a sort feature to sort by either Alphabetical / Highest coin or token balance

> ++ Add in 'importing' an existing portfolio.csv so that you don't have to manually retype out a long string

@pr0d7 I assume that once a sorting argument is presented, we want the original first coin table to sort, as well as the portfolio table? Please let me know if this is incorrect. I will start working on the importing .csv file now.

**Comment by BuildAndDestroy** [comment]
> ++ Add in 'importing' an existing portfolio.csv so that you don't have to manually retype out a long string

This is now pushed to master, version 2.3.5 is now up with bugs fixed. What I like about this is that you can also run an import against the same string of coins. this way you get double tables, one with new data and one from the csv file.
You can always just import the csv file and display a formatted table as well.

**Comment by BuildAndDestroy** [comment]
Ok last request:

> ++Add in a sort feature to sort by either Alphabetical / Highest coin or token balance

I am going to throw a sort feature in and have everything sorted, will close this out once done.

**Comment by BuildAndDestroy** [comment]
> ++Add in a sort feature to sort by either Alphabetical / Highest coin or token balance

Ok 2.4.1 has been pushed to master, you can now sort coins alphabetically. I will add the next version to sort coin/token balance. This is most likely going to be a subparser since we do not want alphabet and coin amount tripping over each other.

**Comment by BuildAndDestroy** [comment]
Closing this one down, the API is dead. Creating a new tool in python3 to work with the new API.
Branch: 2020-api
FYI sort argparser was added, total was added, and limit to 3 decimal places was added. Not sure why I didn't close this issue sooner. Thanks!
